<?xml version="1.0" encoding="UTF-8" ?>
<definitions>
	<message name="getAlumno">
		<part name="n1" type="xsd:string" />
		<part name="n2" type="xsd:string" />
	</message>
	<message>
		<part name="getAlumnoResponse" type="xsd:string" />
	</message>
	<portType name="AlumnoFacadePortType">
		<operation name="getAlumno">
			<input message="typens:getAlumno" />
			<output message="typens:getAlumnoResponse" />
		</operation>
	</portType>
	<binding name="AlumnoFacadeBinding" type="typens:AlumnoFacadePortType">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http" />
	</binding>
</definitions>